In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
sb.set()

In [2]:
df = pd.read_csv('disease_prediction.csv')

In [3]:
df.head()

,patient_id,age,gender,glucose_mg_dl,cholesterol_mg_dl,systolic_bp,diastolic_bp,bmi,heart_rate,smoking,alcohol_consumption,physical_activity,family_history,disease
0,1,32,Male,101,235,152,79,28.5,73,No,Yes,Low,Yes,Yes
1,2,31,Male,124,191,134,77,33.9,71,No,Yes,Low,Yes,Yes
2,3,45,Male,57,141,114,71,27.2,79,Yes,Yes,Low,No,No
3,4,75,Female,69,268,120,82,21.5,61,Yes,Yes,Medium,No,Yes
4,5,53,Male,107,163,131,75,23.3,73,Yes,No,Low,Yes,Yes

In [4]:
df.describe(include = 'all')

,patient_id,age,gender,glucose_mg_dl,cholesterol_mg_dl,systolic_bp,diastolic_bp,bmi,heart_rate,smoking,alcohol_consumption,physical_activity,family_history,disease
count,1000.000000,1000.000000,1000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000,1000,1000,1000,1000
unique,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,2,2,3,2,2
top,NaN,NaN,Female,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,Medium,No,Yes
freq,NaN,NaN,504,NaN,NaN,NaN,NaN,NaN,NaN,503,501,344,504,501
mean,500.500000,51.190000,NaN,104.163000,210.014000,123.893000,81.032000,26.093000,75.968000,NaN,NaN,NaN,NaN,NaN
std,288.819436,19.847514,NaN,25.076508,39.749111,18.701211,9.969974,4.758282,9.902982,NaN,NaN,NaN,NaN,NaN
min,1.000000,18.000000,NaN,30.000000,89.000000,67.000000,49.000000,16.000000,47.000000,NaN,NaN,NaN,NaN,NaN
25%,250.750000,33.000000,NaN,87.000000,183.000000,111.000000,74.000000,22.900000,70.000000,NaN,NaN,NaN,NaN,NaN
50%,500.500000,52.500000,NaN,105.000000,210.500000,124.000000,81.000000,26.000000,76.000000,NaN,NaN,NaN,NaN,NaN
75%,750.250000,69.000000,NaN,121.000000,235.250000,135.000000,88.000000,29.300000,83.000000,NaN,NaN,NaN,NaN,NaN
max,1000.000000,85.000000,NaN,184.000000,339.000000,195.000000,113.000000,41.500000,114.000000,NaN,NaN,NaN,NaN,NaN

In [5]:
new_df = df

In [6]:
new_df = df.drop(['patient_id'], axis = 1)

In [7]:
new_df.head(10)

,age,gender,glucose_mg_dl,cholesterol_mg_dl,systolic_bp,diastolic_bp,bmi,heart_rate,smoking,alcohol_consumption,physical_activity,family_history,disease
0,32,Male,101,235,152,79,28.5,73,No,Yes,Low,Yes,Yes
1,31,Male,124,191,134,77,33.9,71,No,Yes,Low,Yes,Yes
2,45,Male,57,141,114,71,27.2,79,Yes,Yes,Low,No,No
3,75,Female,69,268,120,82,21.5,61,Yes,Yes,Medium,No,Yes
4,53,Male,107,163,131,75,23.3,73,Yes,No,Low,Yes,Yes
5,66,Male,151,209,105,90,23.0,63,No,No,Low,No,Yes
6,76,Male,56,156,128,89,27.0,77,No,Yes,High,No,No
7,64,Male,97,150,112,77,25.4,86,Yes,Yes,Medium,Yes,Yes
8,28,Male,60,222,118,75,27.7,82,Yes,No,Medium,No,No
9,64,Male,128,176,119,85,31.2,85,No,No,High,Yes,Yes

In [8]:
new_df.columns

Index(['age', 'gender', 'glucose_mg_dl', 'cholesterol_mg_dl', 'systolic_bp',
       'diastolic_bp', 'bmi', 'heart_rate', 'smoking', 'alcohol_consumption',
       'physical_activity', 'family_history', 'disease'],
      dtype='object')

In [9]:
df_cols = ['gender', 'smoking', 'alcohol_consumption', 'family_history', 'disease']

In [10]:
for col in df_cols:
    if 'Male' in new_df[col].unique():
        new_df[col] = new_df[col].map({'Male' : 1, 'Female' : 0})
    else:
        new_df[col] = new_df[col].map({'Yes' : 1, 'No' : 0})

In [11]:
new_df['physical_activity'] = new_df['physical_activity'].map({'Low' : 0, 'Medium' : 1, 'High' : 2})

In [12]:
new_df.head()

,age,gender,glucose_mg_dl,cholesterol_mg_dl,systolic_bp,diastolic_bp,bmi,heart_rate,smoking,alcohol_consumption,physical_activity,family_history,disease
0,32,1,101,235,152,79,28.5,73,0,1,0,1,1
1,31,1,124,191,134,77,33.9,71,0,1,0,1,1
2,45,1,57,141,114,71,27.2,79,1,1,0,0,0
3,75,0,69,268,120,82,21.5,61,1,1,1,0,1
4,53,1,107,163,131,75,23.3,73,1,0,0,1,1

In [13]:
##Split the Data

In [14]:
inputs = new_df.drop(['disease'], axis = 1)
target = new_df['disease']

In [15]:
inputs

,age,gender,glucose_mg_dl,cholesterol_mg_dl,systolic_bp,diastolic_bp,bmi,heart_rate,smoking,alcohol_consumption,physical_activity,family_history
0,32,1,101,235,152,79,28.5,73,0,1,0,1
1,31,1,124,191,134,77,33.9,71,0,1,0,1
2,45,1,57,141,114,71,27.2,79,1,1,0,0
3,75,0,69,268,120,82,21.5,61,1,1,1,0
4,53,1,107,163,131,75,23.3,73,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
995,24,1,105,237,86,86,30.9,69,1,1,1,0
996,40,1,120,219,133,72,34.3,92,1,1,1,0
997,44,0,114,273,114,74,36.0,76,0,0,0,0
998,31,1,95,231,130,72,28.2,81,1,1,1,1
999,83,1,109,256,103,86,30.3,64,1,1,2,0

In [16]:
target

0      1
1      1
2      0
3      1
4      1
      ..
995    0
996    0
997    1
998    0
999    1
Name: disease, Length: 1000, dtype: int64

In [17]:
x_train,x_test,y_train,y_test = train_test_split(inputs, target, test_size = 0.2, random_state = 42)

In [18]:
x_train

,age,gender,glucose_mg_dl,cholesterol_mg_dl,systolic_bp,diastolic_bp,bmi,heart_rate,smoking,alcohol_consumption,physical_activity,family_history
29,83,1,125,210,151,79,27.4,103,0,0,2,1
535,61,1,75,276,152,89,31.9,93,0,1,2,1
695,83,0,100,190,107,80,18.3,80,1,1,0,1
557,69,1,135,171,154,79,20.9,91,0,0,0,1
836,54,1,156,216,132,81,16.0,68,0,1,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...
106,80,0,106,158,101,78,30.1,92,1,1,0,0
270,53,1,69,246,112,100,26.6,86,1,1,1,1
860,23,1,53,206,125,89,27.4,85,0,1,2,0
435,54,1,76,201,124,87,29.3,82,0,0,2,1
102,49,0,76,307,127,83,27.4,83,0,0,1,1

In [19]:
numeric_cols = ['age', 'glucose_mg_dl', 'cholesterol_mg_dl', 'systolic_bp', 'diastolic_bp', 'bmi', 'heart_rate']

In [20]:
scaler = StandardScaler()

In [21]:
x_train[numeric_cols] = scaler.fit_transform(x_train[numeric_cols])
x_test[numeric_cols] = scaler.transform(x_test[numeric_cols])

In [22]:
from sklearn.linear_model import LogisticRegression

In [23]:
model = LogisticRegression(random_state = 42)
model.fit(x_train, y_train)
print("Model Training Successful")

Model Training Successful

In [24]:
y_pred = model.predict(x_test)

In [25]:
y_pred

array([0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0])

In [26]:
y_test

521    1
737    1
740    0
660    1
411    0
      ..
408    0
332    1
208    0
613    0
78     0
Name: disease, Length: 200, dtype: int64

In [27]:
df_compare = pd.DataFrame({
    'Actual Disease' : y_test.values,
    'Prediction' : y_pred,
    
})
df_compare.head(15)

    Actual Disease  Prediction
0                1           0
1                1           0
2                0           0
3                1           1
4                0           0
5                1           1
6                1           1
7                1           1
8                1           1
9                1           1
10               0           0
11               0           0
12               0           0
13               0           0
14               0           0

In [28]:
from sklearn.metrics import classification_report, confusion_matrix

In [29]:
cm = confusion_matrix(y_test, y_pred)
cm_df = pd.DataFrame(
    cm,
    index = ['Actual_Healthy (0)', 'Actual_Disease (1)'],
    columns = ['Predicted_Healthy (0)', 'Actual_Disease (1)']
)

In [30]:
cm_df

                    Predicted_Healthy (0)  Actual_Disease (1)
Actual_Healthy (0)                     93                  12
Actual_Disease (1)                     15                  80

In [31]:
print("\n=== CLASSIFICATION REPORT ===")
print(classification_report(y_test, y_pred))

=== CLASSIFICATION REPORT ===
              precision    recall  f1-score   support

           0       0.86      0.89      0.87       105
           1       0.87      0.84      0.86        95

    accuracy                           0.86       200
   macro avg       0.87      0.86      0.86       200
weighted avg       0.87      0.86      0.86       200

In [32]:
from sklearn.metrics import classification_report
import pandas as pd
report_dict = classification_report(y_test, y_pred, output_dict=True)
df_report = pd.DataFrame(report_dict).T
df_report = df_report.round(2)
df_report

              precision  recall  f1-score  support
0                  0.86    0.89      0.87   105.00
1                  0.87    0.84      0.86    95.00
accuracy           0.86    0.86      0.86     0.86
macro avg          0.87    0.86      0.86   200.00
weighted avg       0.87    0.86      0.86   200.00

In [33]:
import joblib

In [34]:
joblib.dump(model, 'heart_disease_detection_model.joblib')

['heart_disease_detection_model.joblib']

In [35]:
joblib.dump(scaler, 'scaler.joblib')

['scaler.joblib']